### ISSUE TITLE
Email to Dazza: This week

### ISSUE THREAD

**Issue by GabrielvonRoda** [ConnectionScience/TweetPing#13]
Repost of Email: 

Hi Dazza, 

I hope this message finds you well. I spoke to Franck and Thomas this AM and unfortunately some coding that went on all weekend for Xerox has made it impossible for us to get the tweet counters ready. As mentioned to you before, this month June is very tight due to stretched resources and deadlines from clients. 

We will work on the tasks we discussed (as posted on Github) and hope to present you with a Version 1 as soon as the client work is out of the way. As mentioned in our call we also hope a new developer will join us soon and then we have some more capacity to execute this for you. 

We are quite excited about the things that came out of our conversation on Thursday and look forward to getting this ready for you for the first test drive. 

Thanks for your understanding and we will be in touch in due course. 

All the best regards, 

Gabriel + Team

**Comment by dazzaji** [comment]
Acknowledged. Thank you for the status update. 

   |  Sent from my iPhone 
   |  Please Forgive Typos

---

   |   Dazza Greenwood, JD
   |   CIVICS.com, Founder & Principal
   |   MIT Media Lab, Visiting Scientist
   |     Vmail: 617.500.3644
   |     Email: dazza@CIVICS.com
   |     Biz: http://CIVICS.com
   |     MIT: https://law.MIT.edu
   |     Me: DazzaGreenwood.com
   |     Twitter: @DazzaGreenwood
   |     Google+: google.com/+DazzaGreenwood
   |     LinkedIn: linkedin.com/in/DazzaGreenwood
   |     GitHub: github.com/DazzaGreenwood/Interface
