### ISSUE TITLE
File sharing  

### ISSUE THREAD

**Issue by GabrielvonRoda** [ConnectionScience/TweetPing#7]
Hello Group, 

I am just looking to upload some files to this but can't seem to find anywhere where this is possible. 

Could anyone please point me to Dazza's video file he originally uploaded - i assume thats the file storage place. 

cheers, 

Gabriel

**Comment by dazzaji** [comment]
Hi there - 

To upload files to the repository, you can use a GitHub application to sync files between your desktop or other file server and your GitHub repository (including uploading new files to the repo).  Here is how:
1. Download client: Download and install the GitHub application on each computer you will use to manage files in the repository.  You will need to remember your GitHub username and password to authorize the client application from your computer to access your GitHub repositories.

Here is a link to the Windows app: https://windows.github.com/  and here is the Mac version: https://mac.github.com/  
1. Clone Repo: Clone the repository to your desktop.  The button for that is on the right side of the screen when you are looking at the repository screen. Also, I included a screen shot of the way to clone the repo to your desktop with this comment on this issue.  Clone just mean "download".  Take note of where on your hard drive you download the repo to... it will come up later when you want to add files to the repository.

![screen shot 2015-06-03 at 11 18 49 am](https://cloud.githubusercontent.com/assets/2357755/7963770/5d1fe39a-09e2-11e5-8579-86d9819a8d0b.png)
1. Test Cloned Repot: In the cloned version of the repo on your desktop, make a small change to a file, such as  by adding a sentence to the README.md file.  

... ran out of time.  please ask your team mate that is technical for a look at the basics of how to use GitHub.  I can do a screencast later and you might be able to use Google to quickly figure this out (but weirdly there seems to be a lack of basic simple instruction on how to use GitHub for non-techies)  I will add a few points and try to finish this up later.
- Then notice in the GitHub client app screen the file shows up as changed.  
- Then "commit" the file (use the commit button in the GitHub client app).  Be sure to add a few words to the comments field with your commit so people have an idea what files you changed and why.  Not a book, just a few words. You can make a few commits before syncing updated files to the GitHub repo or you can just make one at a time.  
- Then "sync" changed file on your desktop to get them onto the repo.
- Then check the repo at GitHub to confirm files are there.
- Once you see how this works then go ahead and put the new files into the directory on your hard drive where you cloned the repo.  You will again see a new file show up in the client app and just commit it and sync it to get it to the GitHub shared repository 
  so the entire team (and the world) can enjoy it.  
- Sync Files on Correct Branch: 
1. Confirm Files Synced on GitHub:
2. Use "Pull Request" to Team Member for Quality Control:

**Comment by dazzaji** [comment]
Here is a YouTube of the video I uploaded: https://youtu.be/Woz120_xTiM

**Comment by GabrielvonRoda** [comment]
thanks Dazza for the very precise briefing. Appreciate it.   I have downloaded the client and will work this way now. 

Gabriel
